In [4]:
# Numpy Vs Lists;

heights = [74, 75, 72, 72, 71] # heights in inchs
print(heights)

#print(heights * 2.54) 
# TypeError: can't multiply sequence by non-int of type 'float'




[74, 75, 72, 72, 71]


In [19]:
#pip install numpy
import numpy as np

np_heights = np.array(heights)
print(np_heights * 2.54) 

# Numpy coms with own set of oper & methods:

list1 = [1,3,9]
list2 = [1,5,4]
print(list1 + list2)

np_l1 = np.array(list1)
np_l2 = np.array(list2)

print(np_l1 + np_l2)
print(type(np_l1))


print("length", "\n", len(np_heights))
print("size", "\n", np_heights.size)
print("shape", "\n", np_heights.shape)

# Conditional Sub setting Arrays:

print("np_heights", "\n", np_heights)

print(np_heights < 73)

print(np_heights[np_heights < 73])

np_heights1 = np_heights[np_heights < 73]

print(np_heights1.size)

print("max:", np_heights.max() )
print("min:", np_heights.min() )
print("avg:", np_heights.mean() )




[187.96 190.5  182.88 182.88 180.34]
[1, 3, 9, 1, 5, 4]
[ 2  8 13]
<class 'numpy.ndarray'>
length 
 5
size 
 5
shape 
 (5,)
np_heights 
 [74 75 72 72 71]
[False False  True  True  True]
[72 72 71]
3
max: 75
min: 71
avg: 72.8


In [31]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[:3])
print(array_1[2:-3])
print(array_1[ : : -2])
print(array_1[ : : 2])
print(array_1[1: : 2])

array_2 = [ 1, 5, 9, 12, 15, 7, 12, 9 ]
m = 6
n = 12

array_2_np = np.array(array_2)
#print(n < array_2_np < m)
print( (array_2_np > n) & (array_2_np < m))
final_array = array_2_np[(array_2_np > n) & (array_2_np < m)] 
print(final_array)


[1, 2, 3]
[3, 5, 4, 6, 7, 8]
[2, 5, 7, 4, 3, 1]
[1, 3, 4, 7, 5, 2]
[2, 5, 6, 8, 3]
[False False False False False False False False]
[]


In [65]:
# Multidimensional Array:

# height & weights of players - 2 D 
players = [(74,180), (74, 215), (72,210), (72,210), (73,180)]  

np_players = np.array(players)

#print(type(np_players))
print((np_players))
print(np_players.shape)
print(np_players.size)
print(np_players.ndim)
print(np_players.dtype)
print(np_players.itemsize) # item stored in bytes

# converting heights to meter & weights to kgs

players_conv = np_players * (0.0254, 0.453592)  

print(players_conv)

print(players_conv[0])       # print row
print(players_conv[0][1])
print(players_conv[0,1])
print(players_conv[:, 0])    # first col

print(np_players[ : , :3])

# height of players > 1.82

print(players_conv[players_conv[:,0]>1.83])
print(players_conv[players_conv[:,0]>1.83].shape)

# skills

skills = np.array(["keeper", "batsman", "bowler", "batsman", "bowler"])
print("array output on diff arry condition")
print(np_players)
print(np_players[skills == "batsman"])

[[ 74 180]
 [ 74 215]
 [ 72 210]
 [ 72 210]
 [ 73 180]]
(5, 2)
10
2
int32
4
[[ 1.8796  81.64656]
 [ 1.8796  97.52228]
 [ 1.8288  95.25432]
 [ 1.8288  95.25432]
 [ 1.8542  81.64656]]
[ 1.8796  81.64656]
81.64656
81.64656
[1.8796 1.8796 1.8288 1.8288 1.8542]
[[ 74 180]
 [ 74 215]
 [ 72 210]
 [ 72 210]
 [ 73 180]]
[[ 1.8796  81.64656]
 [ 1.8796  97.52228]
 [ 1.8542  81.64656]]
(3, 2)
array output on diff arry condition
[[ 74 180]
 [ 74 215]
 [ 72 210]
 [ 72 210]
 [ 73 180]]
[[ 74 215]
 [ 72 210]]


In [66]:
print("array output on diff arry condition")
print(np_players)
print(np_players[skills == "batsman"])

array_2d = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])

print(array_2d)

col_first = array_2d[:,0]
row_first = array_2d[0,:]
col_last =  array_2d[:,-1]
row_last =  array_2d[-1,:]

print(col_first, "\n", row_first, "\n", col_last, "\n", row_last)

array output on diff arry condition
[[ 74 180]
 [ 74 215]
 [ 72 210]
 [ 72 210]
 [ 73 180]]
[[ 74 215]
 [ 72 210]]
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
[11 21 31] 
 [11 12 13 14] 
 [14 24 34] 
 [31 32 33 34]


In [84]:
arr = np.ones(8)

print(arr)
print(arr.dtype)

arr = np.ones(8, dtype=int)

print(arr)
print(arr.dtype)

arr2 = np.ones((5,3), dtype=int)
print(arr2)

print(np.zeros(5))

print(list(range(5)))

print(np.arange(3))
print(np.arange(3.0))

print(np.arange(3, 35, 2))

print(np.random.randint(2, size=10))  # random number array - upper bound < 2 & size is 10
print(np.random.randint(3,5, size=10)) # random number array - lower bound = 3 upper bound < 5 & size is 10

print(np.random.random([3,4]))

print(np.linspace(1, 10, 20))  # array of size 20, between 1 & 10 numbers

[1. 1. 1. 1. 1. 1. 1. 1.]
float64
[1 1 1 1 1 1 1 1]
int32
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[0. 0. 0. 0. 0.]
[0, 1, 2, 3, 4]
[0 1 2]
[0. 1. 2.]
[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]
[0 1 0 1 0 1 0 1 1 1]
[4 3 4 4 4 3 4 4 3 4]
[[0.7975463  0.29772541 0.11670342 0.07258902]
 [0.2717666  0.81133019 0.69714316 0.28574158]
 [0.87474046 0.93440661 0.94626678 0.39978043]]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [95]:
#Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.
def array_zeros(n):

    arr_0 = np.zeros((n,n), dtype=int)
    print(arr_0)
    arr_0[:,0] = 1
    arr_0[:,-1] = 1
    arr_0[0,:] = 1
    arr_0[-1, :] = 1
    print(arr_0)

array_zeros(2)

[[0 0]
 [0 0]]
[[1 1]
 [1 1]]


In [147]:
# mathematics operations on numpy arrays:
arr1 = np.array([10,20,30,40,50])
arr2 = np.arange(5)

print(arr1, "\n", arr2)
print(arr1+arr2)
print(arr2*2)
print(arr2**2)

print(np.power(arr2, 3))

# Stacking of arrays:
#hstack() -- horizantal stacking

print(np.hstack([arr1, arr2]))
print(np.vstack([arr1, arr2]))

#reshape()

print(np.arange(12, dtype=int))
print(np.arange(12).reshape(3,4))

p=np.array([[1, 5],
 [3, 7],
 [4, 9]])


print(np.reshape(p, -1))

q = np.arange(1,21).reshape(4,5)
print(q)
print(q[q%2 != 0])
print(q[q%2 == 0].reshape(5, 2))

print(q[q%2 != 0].reshape(5, 2))

r = np.arange(1,7).reshape(3,2)

print(r)
print(np.reshape(r, (1, -1)).shape)

[10 20 30 40 50] 
 [0 1 2 3 4]
[10 21 32 43 54]
[0 2 4 6 8]
[ 0  1  4  9 16]
[ 0  1  8 27 64]
[10 20 30 40 50  0  1  2  3  4]
[[10 20 30 40 50]
 [ 0  1  2  3  4]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 5 3 7 4 9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  3  5  7  9 11 13 15 17 19]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]
[[1 2]
 [3 4]
 [5 6]]
(1, 6)


In [144]:
l1 = [[7, 13, 14], [18, 10, 17],[11, 12, 19]]
np_l1 = np.array(l1)
np_l1.shape
np_l1

l2 = [16, 6, 1]
np_l2 = np.array(l2)

l3 = [[5, 8, 4, 3]]
np_l3 = np.array(l3)

np2 = np.vstack([np_l1, np_l2])
print(np2.shape)
print(np2)

print(np_l3.transpose())

np.hstack([np2, np_l3.transpose()])



(4, 3)
[[ 7 13 14]
 [18 10 17]
 [11 12 19]
 [16  6  1]]
[[5]
 [8]
 [4]
 [3]]


array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])

In [148]:
# Trigonometric func:

print(np.pi)

3.141592653589793
